name: Update Tutorials JSON

on:
  push:
    paths:
      - 'tutorials/**'

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Generate tutorials.json
        run: |
          python .github/scripts/generate_json.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -f tutorials.json ]; then
            git add tutorials.json
            git diff-index --quiet HEAD || git commit -m "Update tutorials.json"
            git push
          else
            echo "tutorials.json not found, skipping commit"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
